services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434

  client:
    build: ./client
    ports:
      - "80:80"
