services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  client:
    build: ./client
    ports:
      - "80:80"
